### ISSUE TITLE
Isolate Error from Implicitly_animated_list

### ISSUE THREAD

**Issue by asfarul** [themadmrj/chat_ui_kit#44]
Hello, i'm using your plugin since early this year. but i found an error, it happened in chat list and i think that because of implicitly_animated_list plugin. and error appeared if i have 39+ items in chat list.

This is the error from my console log : 

`E/flutter ( 5273): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message: (object extends NativeWrapper - Library:'dart:io' Class: _RandomAccessFileOpsImpl@13069316)
E/flutter ( 5273): #0      Isolate._spawnFunction (dart:isolate-patch/isolate_patch.dart:395:25)
E/flutter ( 5273): #1      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:375:7)
E/flutter ( 5273): #2      compute
package:flutter/…/foundation/_isolates_io.dart:22
E/flutter ( 5273): #3      MyersDiff.diff
package:implicitly_animated_reorderable_list/…/diff/myers_diff.dart:47
E/flutter ( 5273): #4      MyersDiff.withCallback
package:implicitly_animated_reorderable_list/…/diff/myers_diff.dart:24`

and this is my UI with 39+ items in list, when i refresh the ui / set state, the error will appear.
![image](https://user-images.githubusercontent.com/13598088/188354141-96bb3ca3-c902-409b-917d-fbd992bc3017.png)

Thanks before :)

**Comment by Andrflor** [comment]
Have you resolved the issue by any change?

**Comment by asfarul** [comment]
not yet, hope they'll fix this issue ASAP 

> Have you resolved the issue by any change?
